package com.example.infratrackmobile.features.workorder.data.remote.dto

import kotlinx.serialization.Serializable

@Serializable
data class CompleteMaintenanceRequestDto(
    val completionNotes: String,
    // Deprecated: workflow timestamps are generated by the backend.
    val completedAt: String? = null
)
