package com.example.infratrackmobile.features.inspection.data.remote.dto

import kotlinx.serialization.Serializable

@Serializable
data class CompleteInspectionRequestDto(
    val observedCondition: String,
    val observations: String,
    val issueIdentified: Boolean,
    // Deprecated: workflow timestamps are generated by the backend.
    val completedAt: String? = null,
    val answers: List<InspectionAnswerRequestDto>
)
